import React from 'react';
import type { Project, EarlyWarning, RecommendedAction } from '../../types';
import { 
  getOverallRiskMetrics, 
  getRiskDistribution, 
  getRiskTrend 
} from '../../services/analyticsService';
import { 
  calculateExecutivePriorityProjects, 
  generateExecutiveInsights 
} from '../../services/reportService';
import { ReportHeader } from './ReportHeader';
import { ReportFooter } from './ReportFooter';
import { 
  PieChart, Pie, Cell, ResponsiveContainer, Tooltip, 
  LineChart, Line, XAxis, YAxis, CartesianGrid 
} from 'recharts';

interface ExecutiveReportViewProps {
  projects: Project[];
  alerts: EarlyWarning[];
  actions: RecommendedAction[];
  reportId?: string;
  generatedDate?: string;
  generatedBy?: string;
}

export const ExecutiveReportView: React.FC<ExecutiveReportViewProps> = ({
  projects,
  alerts,
  actions,
  reportId = 'REP-EXEC-2026-09',
  generatedDate = new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'long', year: 'numeric' }),
  generatedBy = 'Senior Director (IPMD)'
}) => {
  const metrics = getOverallRiskMetrics(projects);
  const distribution = getRiskDistribution(projects);
  const trend = getRiskTrend(projects, '6M');
  const priorityProjects = calculateExecutivePriorityProjects(projects, alerts, actions);
  const insights = generateExecutiveInsights(projects, alerts);

  const activeWarningsCount = alerts.filter(a => a.status === 'New' || a.status === 'Open').length;

  return (
    <div className="bg-white text-slate-900 rounded-xl p-8 shadow-xl border border-slate-200 max-w-5xl mx-auto space-y-6 print:shadow-none print:border-none print:p-0">
      
      {/* Header */}
      <ReportHeader 
        title="Executive Project Monitoring Overview" 
        subtitle="Portfolio-Wide Predictive Monitoring Briefing for Senior Leadership"
        reportId={reportId}
        date={generatedDate}
      />

      {/* Scope Card */}
      <div className="bg-slate-50 border border-slate-300 rounded p-3 text-xs grid grid-cols-2 sm:grid-cols-4 gap-4 print:bg-slate-50">
        <div>
          <div className="text-[10px] font-bold text-slate-500 uppercase">Generated By</div>
          <div className="font-bold text-slate-900 mt-0.5">{generatedBy}</div>
        </div>
        <div>
          <div className="text-[10px] font-bold text-slate-500 uppercase">Monitored Portfolio Outlay</div>
          <div className="font-mono font-bold text-slate-900 mt-0.5">₹{projects.reduce((a, b) => a + b.originalBudgetCr, 0).toLocaleString()} Cr</div>
        </div>
        <div>
          <div className="text-[10px] font-bold text-slate-500 uppercase">Average Risk Score</div>
          <div className="font-mono font-bold text-amber-700 mt-0.5">{metrics.averageRiskScore} / 100</div>
        </div>
        <div>
          <div className="text-[10px] font-bold text-slate-500 uppercase">Active Portfolio Warnings</div>
          <div className="font-bold text-red-700 mt-0.5">{activeWarningsCount} Active Alerts</div>
        </div>
      </div>

      {/* 6 Executive Key Metric Cards */}
      <div className="grid grid-cols-2 sm:grid-cols-6 gap-3">
        <div className="bg-slate-50 border border-slate-300 p-2.5 rounded text-center">
          <div className="text-[10px] font-bold text-slate-500 uppercase">Total Projects</div>
          <div className="text-base font-black text-slate-900 mt-0.5">{projects.length}</div>
        </div>

        <div className="bg-slate-50 border border-slate-300 p-2.5 rounded text-center">
          <div className="text-[10px] font-bold text-slate-500 uppercase">High Risk</div>
          <div className="text-base font-black text-red-700 mt-0.5">{metrics.highRiskCount}</div>
        </div>

        <div className="bg-slate-50 border border-slate-300 p-2.5 rounded text-center">
          <div className="text-[10px] font-bold text-slate-500 uppercase">Medium Risk</div>
          <div className="text-base font-black text-amber-600 mt-0.5">{metrics.mediumRiskCount}</div>
        </div>

        <div className="bg-slate-50 border border-slate-300 p-2.5 rounded text-center">
          <div className="text-[10px] font-bold text-slate-500 uppercase">Low Risk</div>
          <div className="text-base font-black text-emerald-700 mt-0.5">{metrics.lowRiskCount}</div>
        </div>

        <div className="bg-slate-50 border border-slate-300 p-2.5 rounded text-center">
          <div className="text-[10px] font-bold text-slate-500 uppercase">Delay Risk</div>
          <div className="text-base font-black text-amber-800 mt-0.5">{metrics.scheduleDelayRiskCount}</div>
        </div>

        <div className="bg-slate-50 border border-slate-300 p-2.5 rounded text-center">
          <div className="text-[10px] font-bold text-slate-500 uppercase">Cost Risk</div>
          <div className="text-base font-black text-teal-800 mt-0.5">{metrics.costOverrunRiskCount}</div>
        </div>
      </div>

      {/* Executive Key Insights Section */}
      <section className="bg-teal-50 border-l-4 border-teal-600 p-4 rounded-r">
        <h3 className="text-xs font-extrabold text-teal-950 uppercase tracking-wider mb-2">
          Key Data-Driven Insights
        </h3>
        <ul className="space-y-1.5 text-xs text-slate-800 font-medium">
          {insights.map((insight, idx) => (
            <li key={idx} className="flex items-start space-x-2">
              <span className="text-teal-700 font-bold">•</span>
              <span>{insight}</span>
            </li>
          ))}
        </ul>
      </section>

      {/* Charts Row: Risk Distribution & Risk Trend */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        
        <div className="bg-slate-50 border border-slate-300 p-3 rounded text-xs">
          <div className="text-[11px] font-extrabold text-slate-900 uppercase tracking-wide mb-2 text-center">
            Overall Risk Distribution
          </div>
          <div className="h-44 w-full flex items-center justify-center">
            <ResponsiveContainer width="100%" height="100%">
              <PieChart>
                <Pie 
                  data={distribution} 
                  dataKey="count" 
                  nameKey="category" 
                  cx="50%" 
                  cy="50%" 
                  outerRadius={60} 
                  label={(entry: any) => `${entry.category}: ${entry.count}`}
                >
                  {distribution.map((entry, index) => (
                    <Cell key={`cell-${index}`} fill={entry.color} />
                  ))}
                </Pie>
                <Tooltip contentStyle={{ backgroundColor: '#0f172a', borderColor: '#334155', color: '#fff', fontSize: '11px' }} />
              </PieChart>
            </ResponsiveContainer>
          </div>
        </div>

        <div className="bg-slate-50 border border-slate-300 p-3 rounded text-xs">
          <div className="text-[11px] font-extrabold text-slate-900 uppercase tracking-wide mb-2 text-center">
            Portfolio Average Risk Trend (6-Month Horizon)
          </div>
          <div className="h-44 w-full">
            <ResponsiveContainer width="100%" height="100%">
              <LineChart data={trend.points} margin={{ top: 10, right: 20, left: -20, bottom: 5 }}>
                <CartesianGrid strokeDasharray="3 3" stroke="#cbd5e1" />
                <XAxis dataKey="date" stroke="#475569" tick={{ fontSize: 10 }} />
                <YAxis domain={[0, 100]} stroke="#475569" tick={{ fontSize: 10 }} />
                <Tooltip contentStyle={{ backgroundColor: '#0f172a', borderColor: '#334155', color: '#fff', fontSize: '11px' }} />
                <Line type="monotone" dataKey="avgRiskScore" stroke="#0d9488" strokeWidth={3} name="Avg Risk Score" />
              </LineChart>
            </ResponsiveContainer>
          </div>
        </div>

      </div>

      {/* EXECUTIVE PRIORITY SECTION: "Projects Requiring Immediate Attention" */}
      <section className="page-break-inside-avoid">
        <div className="border-b border-slate-300 pb-2 mb-3 flex items-center justify-between">
          <h3 className="text-xs font-black text-slate-950 uppercase tracking-wider">
            Projects Requiring Immediate Attention (Ranked Priority Matrix)
          </h3>
          <span className="text-[10px] text-slate-500 font-mono font-semibold">
            Formula: Risk (45%) + Gap (35%) + Warning (12%) + Cost (8%)
          </span>
        </div>

        <div className="border border-slate-300 rounded overflow-hidden text-xs">
          <table className="w-full text-left border-collapse">
            <thead>
              <tr className="bg-slate-100 text-slate-800 text-[10px] uppercase border-b border-slate-300 font-bold">
                <th className="p-2 border-r border-slate-300 text-center w-12">Priority</th>
                <th className="p-2 border-r border-slate-300">Project Name</th>
                <th className="p-2 border-r border-slate-300 text-center w-16">Risk Score</th>
                <th className="p-2 border-r border-slate-300">Primary Risk</th>
                <th className="p-2 border-r border-slate-300 text-center w-20">Progress</th>
                <th className="p-2 border-r border-slate-300">Active Warning</th>
                <th className="p-2">Recommended Priority Action</th>
              </tr>
            </thead>
            <tbody>
              {priorityProjects.slice(0, 5).map((item) => (
                <tr key={item.project.id} className="border-b border-slate-200 text-slate-900 last:border-none">
                  <td className="p-2 text-center font-bold font-mono border-r border-slate-200 bg-slate-50">
                    #{item.priorityRank}
                  </td>
                  <td className="p-2 border-r border-slate-200 font-bold">
                    <div>{item.project.name}</div>
                    <div className="text-[10px] font-mono font-normal text-slate-600">{item.project.code} • {item.project.sector}</div>
                  </td>
                  <td className="p-2 text-center font-mono font-extrabold border-r border-slate-200 text-amber-800">
                    {item.riskScore}
                  </td>
                  <td className="p-2 border-r border-slate-200 font-semibold">{item.primaryRisk}</td>
                  <td className="p-2 text-center border-r border-slate-200 text-[11px]">
                    <div className="font-bold">{item.project.actualPhysicalProgress}%</div>
                    <div className="text-[9px] text-slate-500">Gap: -{item.progressGap}%</div>
                  </td>
                  <td className="p-2 border-r border-slate-200 text-[11px] text-amber-900 font-medium">
                    {item.activeWarningTitle}
                  </td>
                  <td className="p-2 text-[11px] font-medium text-slate-800">
                    {item.recommendedActionTitle}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>

      {/* Recent Warnings & Priority Actions Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4 page-break-inside-avoid text-xs">
        
        {/* Recent Warnings */}
        <div className="border border-slate-300 rounded overflow-hidden">
          <div className="bg-slate-100 p-2 font-bold text-slate-900 uppercase text-[10px] border-b border-slate-300">
            Recent Active Early Warnings ({alerts.length})
          </div>
          <div className="divide-y divide-slate-200">
            {alerts.slice(0, 3).map((a) => (
              <div key={a.id} className="p-2.5">
                <div className="flex justify-between font-bold text-slate-900">
                  <span>{a.title}</span>
                  <span className="text-[10px] text-red-700 uppercase font-mono">{a.severity}</span>
                </div>
                <div className="text-[11px] text-slate-600 mt-0.5">{a.projectName} • {a.assignedOfficer}</div>
              </div>
            ))}
          </div>
        </div>

        {/* Priority Actions */}
        <div className="border border-slate-300 rounded overflow-hidden">
          <div className="bg-slate-100 p-2 font-bold text-slate-900 uppercase text-[10px] border-b border-slate-300">
            Priority Prescriptive Actions ({actions.length})
          </div>
          <div className="divide-y divide-slate-200">
            {actions.slice(0, 3).map((act) => (
              <div key={act.id} className="p-2.5">
                <div className="flex justify-between font-bold text-slate-900">
                  <span>{act.title}</span>
                  <span className="text-[10px] text-teal-700 uppercase font-mono">{act.priority}</span>
                </div>
                <div className="text-[11px] text-slate-600 mt-0.5">{act.projectName} • {act.assignedTo}</div>
              </div>
            ))}
          </div>
        </div>

      </div>

      {/* Footer */}
      <ReportFooter 
        signatory="Joint Director General (IPMD)"
        designation="Ministry of Statistics & Programme Implementation"
      />

    </div>
  );
};
