import React from 'react';
import type { GeneratedReport } from '../../types';

interface ReportMetadataCardProps {
  report: GeneratedReport;
}

export const ReportMetadataCard: React.FC<ReportMetadataCardProps> = ({ report }) => {
  return (
    <div className="bg-slate-50 border border-slate-300 rounded-lg p-4 mb-6 text-slate-900 text-xs grid grid-cols-2 sm:grid-cols-4 gap-4 print:bg-white print:border-slate-300">
      <div>
        <div className="text-[10px] font-bold text-slate-500 uppercase tracking-wider">Report ID</div>
        <div className="font-mono font-bold text-slate-900 mt-0.5">{report.id}</div>
      </div>

      <div>
        <div className="text-[10px] font-bold text-slate-500 uppercase tracking-wider">Generated Date</div>
        <div className="font-semibold text-slate-800 mt-0.5">{report.generatedDate}</div>
      </div>

      <div>
        <div className="text-[10px] font-bold text-slate-500 uppercase tracking-wider">Generated By</div>
        <div className="font-semibold text-slate-800 mt-0.5">{report.generatedBy}</div>
      </div>

      <div>
        <div className="text-[10px] font-bold text-slate-500 uppercase tracking-wider">Data Period / Scope</div>
        <div className="font-semibold text-slate-800 mt-0.5 truncate">{report.dataPeriod}</div>
      </div>
    </div>
  );
};
